version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./data-db/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      retries: 5
    restart: always
    networks:
      - odoo-net

  odoo:
    build: .
    depends_on:
      db:
        condition: service_healthy   # âœ… Wait for Postgres to be ready
    ports:
      - "8069:8069"
    volumes:
      - ./extra_addons:/extra-addons
      - ./config/odoo.conf:/opt/odoo/odoo.conf
      - ./odoo-data:/opt/odoo/data
      - ./odoo-log:/var/log/odoo
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    command: >
      python odoo/odoo-bin -c /etc/odoo/odoo.conf
      -d odoo --db_host=db --db_port=5432 --db_user=odoo --db_password=odoo
      -u jo_assessment_base,jo_product_brand,import_bom
    restart: always
    networks:
      - odoo-net

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"   # access pgAdmin at http://localhost:5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    restart: always
    networks:
      - odoo-net

volumes:
  odoo-data:
  pgadmin-data:

networks:
  odoo-net:
